# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^docs/|/migrations/"
default_stages: [pre-commit]
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: ^pnpm-lock.yaml
      - id: check-added-large-files
        args: ["--maxkb=750"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-symlinks
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - --line-length=100
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: python
        language_version: python3.10
        types: [python]
        require_serial: true
        entry: bash .pre-commit-run.sh ruff check
      # - id: mypy
      #   name: mypy
      #   entry: bash .pre-commit-run.sh mypy
      #   language: python
      #   language_version: python3.10
      #   types: [python]
      #   require_serial: true
      #   additional_dependencies: []
      #   args:
      #     - --show-error-codes
      #     - --ignore-missing-imports
      #     - --disallow-untyped-defs

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
